name: todo_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: 1.2.0
  get_it: 7.6.2
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  json_annotation: 4.8.1
  injectable: 2.3.0
  dartz: 0.10.1
  http: 1.1.0
  hive_flutter: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  bloc_test: 9.1.4
  mocktail: 1.0.0
  json_serializable: 6.7.1
  build_runner: 2.4.6
  injectable_generator: 2.4.0
  hive_generator: 2.0.1

flutter:
  uses-material-design: true

scripts: scripts.yaml
